# Termhome Bookmarks Configuration
---
- Documentation:
    - Termhome Docs:
        icon: github
        href: https://github.com/deblasis/termhome
        description: Termhome documentation

- Search Engines:
    - Google:
        abbr: G
        icon: google
        href: https://google.com
        description: Google Search
    - DuckDuckGo:
        abbr: DDG
        icon: duckduckgo
        href: https://duckduckgo.com
        description: Privacy-focused search engine
    - Perplexity:
        abbr: P
        icon: perplexity
        href: https://perplexity.com
        description: AI-powered search engine
