# Direct Docker socket connection
local-docker:
  socket: /var/run/docker.sock
  interval: 10  # Check every 10 seconds

# Connection via Docker proxy (uncomment to enable)
# docker-proxy:
#   host: dockerproxy
#   port: 2375
