# Termhome Services Configuration

Applications:
  - name: GitHub
    href: https://github.com
    description: Where the world builds software
    siteMonitor:
      url: https://github.com
      method: HEAD
      timeout: 5
      interval: 60
      expectedCodes: [200, 301, 302]
  - name: ChatGPT
    href: https://chatgpt.com
    description: The AI chatbot
    ping:
      host: chatgpt.com
      count: 3
      interval: 60

Development Tools:
  - name: V0
    href: https://v0.dev
    siteMonitor:
      url: https://v0.dev
      method: GET
      timeout: 10
      interval: 60
      expectedCodes: [429]
      headers:
        User-Agent: "Termhome/1.0"

Monitoring:
  - name: Local Network
    description: Local network status
    ping:
      host: 192.168.1.1
      interval: 30
