# Termhome Services Configuration
---
- Applications:
    - GitHub:
        icon: github
        href: https://github.com
        description: Where the world builds software
        siteMonitor: https://github.com
        siteMonitorMethod: HEAD
        siteMonitorTimeout: 5
        siteMonitorInterval: 60
        siteMonitorExpectedCodes: [200, 301, 302]
    - ChatGPT:
        icon: openai
        href: https://chatgpt.com
        description: The AI chatbot
        ping: chatgpt.com
        pingCount: 3
        pingInterval: 60

- Development Tools:
    - V0:
        icon: v0
        href: https://v0.dev
        siteMonitor: https://v0.dev
        siteMonitorMethod: GET
        siteMonitorTimeout: 10
        siteMonitorInterval: 60
        siteMonitorExpectedCodes: [429]
        siteMonitorHeaders:
          User-Agent: "Termhome/1.0"

- Monitoring:
    - Local Network:
        icon: network
        description: Local network status
        ping: 192.168.1.1
        pingInterval: 30
