# This workflow will builds and tests Termdash.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master", "devel"]
  pull_request:
    branches: ["master", "devel"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24", "stable"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Format
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Lint
        run: diff -u <(echo -n) <(golint ./...)
